### ISSUE TITLE
Congrats! But where is the module?

### ISSUE THREAD

**Issue by bd0bd** [backdrop-contrib/seo_meta#1]
My congratulations!
It is a right step to rename the module.

Well, but where is the module? I do not see anything but the 2 files at https://github.com/backdrop-contrib/seo_meta

**Comment by findlabnet** [comment]
Thanks @bd0bd, this repository was just created for new module which haven't released yet. But over next hours you may try to use it for your project(s). I'll let you know by closing this issue.

**Comment by bd0bd** [comment]
I see :smile: 
Thank you!

**Comment by bd0bd** [comment]
BTW, please look at this my issue https://github.com/backdrop/backdrop-issues/issues/2031
May be it would be interesting for you to make this option.

**Comment by findlabnet** [comment]
@bd0bd, there is not official release yet, but if you want, you can try this module.
