### ISSUE TITLE
Undefined function taxonomy_get_vocabularies()

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/seo_meta#11]
Without the Taxonomy module enabled, SEO Meta Tags still displays a 'Taxonomy Pages' tab at admin/config/metadata/seo_meta which, when clicked, gives a white screen. Apache logs show the following error:

> PHP Fatal error:  Call to undefined function taxonomy_get_vocabularies() in /[SNIP]/modules/seo_meta/seo_meta.admin.inc on line 378

**Comment by findlabnet** [comment]
@BWPanda , thank you for reporting this bug. I'll fix it as soon as I can, I just waiting when you finish your (very useful) researches of this module (e.g. all new issues opened by you).

**Comment by ghost** [comment]
@findlabnet No worries. Think I'm done for now :wink:

**Comment by findlabnet** [comment]
Fixed in [latest release](https://github.com/backdrop-contrib/seo_meta/releases/download/1.x-1.0.13/seo_meta.zip).
@BWPanda, thanks again.
