### ISSUE TITLE
Tabs disappear on Front Page admin form

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/seo_meta#12]
When you go to admin/config/metadata/seo_meta, there are 4 tabs at the top of the page:

- Default meta tags
- Front page
- Views pages
- Taxonomy pages

When you click on the Front Page tab, the resulting page has no tabs anymore.

**Comment by findlabnet** [comment]
Fixed in [latest release](https://github.com/backdrop-contrib/seo_meta/releases/download/1.x-1.0.13/seo_meta.zip).
@BWPanda, thanks again.
