### ISSUE TITLE
Open Graph image disappears

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/seo_meta#19]
OG images disappear once set. I guess it's something related to cron, as it is not immediate. Seo data is ok in data base, but files in files/og_images are missing. Anyone having this same issue?

**Comment by robertgarrigos** [comment]
I realise that once uploaded an OG image, it gets listed in /admin/content/files as temporary file. Why is that? All the others are permanent.

**Comment by findlabnet** [comment]
Thank you for reporting, @robertgarrigos. You are first, who report  this issue, I'll check it ASAP.

**Comment by robertgarrigos** [comment]
Also that image has a use count of zero. Now it's gone again. Coul it be that backdrop, during crons, delete unused images (with zero use count)?

**Comment by findlabnet** [comment]
You right, there is wrong file saving behavior, I'll fix it tomorrow.

**Comment by robertgarrigos** [comment]
I realize that you changed seo_meta_node_presave() function to seo_meta_node_insert(). then when you update the node with a new og image the insert hook doesn't take place. By changing back to _presave I fixed this problem. Any reason to change it to _insert()?? I filled a PR.

**Comment by findlabnet** [comment]
Tomorrow is not tonight ;-) thank you!

**Comment by robertgarrigos** [comment]
``Tomorrow is not tonight``: sorry, I was sending comments without refreshing the page and didn't see yours :-)
