### ISSUE TITLE
Page title does not work

### ISSUE THREAD

**Issue by bd0bd** [backdrop-contrib/seo_meta#2]
Page title does not work.

Meta keywords does not exist.

**Comment by findlabnet** [comment]
> Meta keywords does not exist.

Are you enabled this in main settings? (Checkbox "Use keywords meta tag")

> Page title does not work.

More info, please

**Comment by bd0bd** [comment]
Hm, are you sure this is a good idea to hide Meta keywords field?
In my mind Meta keywords and Meta description are like brothers and should be activated both by a default.

Nothing works! Nothing changes.

I have on this site base_meta-1.x deactivated. May be  it is the reason I have it in the modules folder (should I delete it)? Or it is because of the database?

**Comment by findlabnet** [comment]
As I noted in this checkbox description, as far as I know - meta keywords have not value for modern search engines, except negative when used in too aggressive mode. 
About "Nothing works!". I need some more information, for example: error messages if any, log messages or just scenario what do you do and what you see. In which directory was installed new module? Old one do not must be deleted (different config files and DB tables), disable it is enough to not to be confused by similar admin forms. Maybe just "flush all cashes" should clean a picture?

**Comment by bd0bd** [comment]
Well, it does not work on the home page - nothing happens (it does not add any meta), no any errors.
But it works on other pages.

```
Maybe just "flush all cashes" should clean a picture?
```

I do it every time of cause.

**Comment by findlabnet** [comment]
Home page - how it set - as in default install or some other path (node, view page)?

**Comment by bd0bd** [comment]
/admin/config/system/site-information
FRONT PAGE
Default front page
http://domain.com/home

SYSTEM PATH
node/1

**Comment by bd0bd** [comment]
May be it will help to understand.
I have loged out and when I have loged in then I see this errors:

Notice: Undefined property: stdClass::$type in seo_meta_preprocess_page() (line 756 of /home/www/domain.com/modules/seo_meta-master/seo_meta.module).
Notice: Undefined property: stdClass::$id in seo_meta_preprocess_page() (line 756 of /home/www/domain.com/modules/seo_meta-master/seo_meta.module).
Notice: Undefined property: stdClass::$type in seo_meta_preprocess_page() (line 773 of /home/www/domain.com/modules/seo_meta-master/seo_meta.module).
Notice: Undefined property: stdClass::$type in seo_meta_preprocess_page() (line 773 of /home/www/domain.com/modules/seo_meta-master/seo_meta.module).
Notice: Undefined property: stdClass::$type in seo_meta_build_page_tags() (line 669 of /home/www/domain.com/modules/seo_meta-master/seo_meta.module).
Notice: Undefined property: stdClass::$id in seo_meta_build_page_tags() (line 669 of /home/www/domain.com/modules/seo_meta-master/seo_meta.module).

**Comment by findlabnet** [comment]
Thanks, I'll check it today, but anyway - when you unzip code - make sure module directory should be (re)named as "seo_meta" instead "seo_meta-master" given by Github.

**Comment by bd0bd** [comment]
```
module directory should be (re)named as "seo_meta"
```

Ok. Thank you!

**Comment by bd0bd** [comment]
When I log out and then go to the login page — http://domain.com/user — I see these errors:

Notice: Undefined property: stdClass::$type in seo_meta_preprocess_page() (line 756 of /home/www/domain.com/modules/seo_meta/seo_meta.module).
Notice: Undefined property: stdClass::$id in seo_meta_preprocess_page() (line 756 of /home/www/domain.com/modules/seo_meta/seo_meta.module).
Notice: Undefined property: stdClass::$type in seo_meta_preprocess_page() (line 773 of /home/www/domain.com/modules/seo_meta/seo_meta.module).
Notice: Undefined property: stdClass::$type in seo_meta_preprocess_page() (line 773 of /home/www/domain.com/modules/seo_meta/seo_meta.module).
Notice: Undefined property: stdClass::$type in seo_meta_build_page_tags() (line 669 of /home/www/domain.com/modules/seo_meta/seo_meta.module).
Notice: Undefined property: stdClass::$id in seo_meta_build_page_tags() (line 669 of /home/www/domain.com/modules/seo_meta/seo_meta.module).

**Comment by findlabnet** [comment]
Thanks, will be fixed today.

**Comment by findlabnet** [comment]
@bd0bd, thank you for your QA works! You can continue with latest code. :-)

**Comment by bd0bd** [comment]
Hm ...
Impossible to FTP 4 files.
I try to do it 20 minutes.
I use FTP for 20 years.
May be something is wrong with folders and files (CHMOD etc)?

**Comment by bd0bd** [comment]
seo_meta.js
seo_meta.css
seo_meta.settings.json
seo_meta.info

**Comment by bd0bd** [comment]
This happens again and again, repeatedly and repeatedly.
5 files downloads successfully and the 4 files can not be uploaded.

**Comment by findlabnet** [comment]
Only .info file from your set was changed today. I do not use FTP, so can't help with it. Maybe you can try download https://github.com/backdrop-contrib/seo_meta/archive/master.zip to your local machine, then rename/repack and upload as one file and unpack on the server.

**Comment by bd0bd** [comment]
Well finally I have this error at /admin/config/search/seo_meta/home

Warning: Missing argument 1 for seo_meta_custom_item_tags_edit(), called in /home/www/domain.com/modules/seo_meta/seo_meta.admin.inc on line 299 and defined in seo_meta_custom_item_tags_edit() (line 448 of /home/www/domain.com/modules/seo_meta/seo_meta.admin.inc).
Warning: Missing argument 2 for seo_meta_custom_item_tags_edit(), called in /home/www/domain.com/modules/seo_meta/seo_meta.admin.inc on line 299 and defined in seo_meta_custom_item_tags_edit() (line 448 of /home/www/domain.com/modules/seo_meta/seo_meta.admin.inc).
Notice: Undefined offset: 5 in seo_meta_custom_item_tags_edit() (line 458 of /home/www/domain.com/modules/seo_meta/seo_meta.admin.inc).
Language with code "" do not enabled for this site!

**Comment by findlabnet** [comment]
Thanks, case with only one language enabled was not tested for weeks. I'll fix it too.

**Comment by bd0bd** [comment]
Why you have added this tab HOMEPAGE at /admin/config/search/seo_meta?
In base_meta there was no this tab and however it was possible to make custom metas directly from the home page.

**Comment by findlabnet** [comment]
If you have more than one language on site - you have same number of homepages - possible edit tags for each one.

**Comment by bd0bd** [comment]
It's very nice! I will need it in future :)

**Comment by bd0bd** [comment]
Another issue — there is no default page titles (on any page) but website title if seo_meta Define tags for page of this node is not used.

**Comment by findlabnet** [comment]
>  I'll fix it too.

But tomorrow. :(

**Comment by bd0bd** [comment]
This is not a problem. It is ok.
For now I use base_meta :smile:

**Comment by findlabnet** [comment]
Two bugs found yesterday are fixed. Welcome to next tests.

**Comment by bd0bd** [comment]
Thank you!

"If selected, default values of meta tags will not be used for this node." is displayed on all pages.
It should not.

On the home page would be right to remove option "Define tags for page of this node" and say that it should be configured at /admin/config/search/seo_meta/home/en
Would be right to remove /en if website is not multilanguage. It should be added if multilanguage is activated.

On this page /admin/config/search/seo_meta/home/en there is no tabs
DEFAULT META TAGS
HOMEPAGE
VIEWS PAGES
TAXONOMY PAGES
but the tabs exist on all other pages:

/admin/config/search/seo_meta/views
/admin/config/search/seo_meta/taxonomy

**Comment by bd0bd** [comment]
The problem exist - home page title can not be changed.

**Comment by findlabnet** [comment]
> The problem exist - home page title can not be changed.

???

**Comment by bd0bd** [comment]
It does not work.
I change it on /admin/config/search/seo_meta/home/en but I have the same default title.
Nothing changes.

**Comment by findlabnet** [comment]
@bd0bd , please more info: config of home page, where and what you set and what you get.
BTW, if you have more than one question or issue please put them to ordered list and I can answer by numbers without citing.

**Comment by bd0bd** [comment]
@/admin/config/system/site-information
Default front page: home

I change title at /admin/config/search/seo_meta/home/en but title does not changes.

No any errors happens.

**Comment by findlabnet** [comment]
"home" is URL alias for some node? Same config work fine for me. I'll check it on clean install later. Make sure you have latest module files.

**Comment by bd0bd** [comment]
/admin/config/system/site-information
FRONT PAGE
Default front page
http://domain.com/home

SYSTEM PATH
node/1

**Comment by bd0bd** [comment]
I have downloaded from https://github.com/backdrop-contrib/seo_meta

**Comment by findlabnet** [comment]
Should work for now. Some changes in UI.

**Comment by bd0bd** [comment]
Thank you! It works now.

What about adding tabs at /admin/config/search/seo_meta/home/en the same like we have it on other pages at /admin/config/search/seo_meta
DEFAULT META TAGS
HOMEPAGE
VIEWS PAGES
TAXONOMY PAGES

**Comment by findlabnet** [comment]
About tabs. 
When you edit tags for one of views pages or taxonomy term pages, you also can not see them because you got endpoint form. 
If you use more than one language, on "Front page" you should get set of links to such endpoint forms and all tabs is visible. 
Anyway, for navigation purpose you have breadcrumbs on top.

**Comment by bd0bd** [comment]
I have no problems with navigation.
I talk about usability :smile: 
User would expect to see these tabs when exploring the pages.
It is just my opinion.
This is not too important issue at this point.

---

I think it is better to reshape a little bit this content:

```
This node is set as site front page, so for this page front page meta tags will be used.
```

Also the current green solution is not appropriate one at this case I think.

**Comment by findlabnet** [comment]
Thanks. 
Reason of placing all special pages (front, views, taxonomy) in one isolated place -  independent from their APIs which is subject of changes.
Your suggestion for shape of this phrase?
Green - this is status message. You think yellow warning was best for this information?

**Comment by bd0bd** [comment]
Yes, I suggest to reshape the phrase and wording in more usability way.

Yes, I think yellow warning is more appropriate one.
But may be it is better do not use any of these ones.
Just to make a plain text.

**Comment by findlabnet** [comment]
OK, this issue can be closed.
