### ISSUE TITLE
Canonical URL HTTPS Missing when Visit with HTTPS

### ISSUE THREAD

**Issue by domaingood** [backdrop-contrib/seo_meta#21]
When Visit with SSL https://www.exmample.com
Still Canonical URL without https:
<link rel="canonical" href="http://www.exmample.com" />

**Comment by findlabnet** [comment]
Thank you for reporting, I'll check it ASAP.

**Comment by findlabnet** [comment]
Hello, @domaingood , to resolve your problem please visit <your_domain>/admin/config/urls/settings and set up option "Use HTTPS for canonical URLs".

**Comment by domaingood** [comment]
I want When visit without HTTPS then HTTP for canonical URLs.
When visit HTTPS  then HTTPS for canonical URLs.

Please check Metatag module by Jen Lampton

**Comment by findlabnet** [comment]
As I described above, this module uses the Backdrop's system setting to process the canonical URLs protocol.
Knowing that most browsers will soon end support for unsafe URLs makes me leave it as it is.
