### ISSUE TITLE
Meta description 160-200 characters max

### ISSUE THREAD

**Issue by domaingood** [backdrop-contrib/seo_meta#22]
Text you trying fill in to field "Meta description" is too long!

160-200 characters max

Please add 300 characters max

**Comment by findlabnet** [comment]
You are first with such request. 
How about this
https://yoast.com/academy/all-around-seo-training/meta-description-length/
(and many others) recommendations?

**Comment by domaingood** [comment]
How can I add Complete List of HTML Meta Tags in Backdrop.Please make more general field for meta tag
https://gist.github.com/lancejpollard/1978404

**Comment by findlabnet** [comment]
Thank you for your interest in this module.
This module is intended to be a simple alternative for people who need a small basic set of meta tags with simple processing.
If this is not what you want, you can try more complex solutions like the ones you mentioned earlier.
