### ISSUE TITLE
meta_og_description gives sql error if too long - should give UI feedback instead

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/seo_meta#24]
OG Description field gives no clue as to a maximum number of characters.  The phrase between 2-4 sentences is too vague.  

Added description that was 940 characters long.
Error
SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'meta_og_description' at row 1 - details redacted for privacy

When reduced to 200 (same as description above) it saves.  The help should give the maximum number of characters and the validation should check that before trying to save to the database.

**Comment by findlabnet** [comment]
Thanks for for reporting, I'll take care of it as soon as possible.

**Comment by findlabnet** [comment]
Thank you, fixed in new release 1.x-1.0.15
