### ISSUE TITLE
Put all config into config files

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/seo_meta#25]
I note some config is in settings but some is in database.  Is there a reason for this?

It would be easier for deployment and version control if all could be in config

**Comment by findlabnet** [comment]
Thanks for for reporting, I'll check it as soon as possible.

**Comment by findlabnet** [comment]
@yorkshire-pudding, thank you for your valuable help and interest.
In the database, I only store the tag values themselves, which are not "settings", so it's not clear to me what you mean.

**Comment by yorkshire-pudding** [comment]
I think metatags and metatag patterns are config; they're not content.  As these are set at a high level rather than per node and they're also not a state, I think they should be in config.  In the `metatag` module, all the tags and settings are stored in config.

**Comment by findlabnet** [comment]
> This module is NOT intended to completely replace or repeat all the functions of its "big brother" ("Metatag" module) - only the necessary minimum set of functions.
