### ISSUE TITLE
Untranslatable form item descriptions

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/seo_meta#26]
Following descriptions aren't wrapped in `t()` and hence aren't translatable:

- https://github.com/backdrop-contrib/seo_meta/blob/master/seo_meta.admin.inc#L91
- https://github.com/backdrop-contrib/seo_meta/blob/master/seo_meta.admin.inc#L553
- https://github.com/backdrop-contrib/seo_meta/blob/master/seo_meta.module#L226

The solution is easy, though. Wrap it in `t()` :wink:

**Comment by findlabnet** [comment]
Thank you for reporting, I'll take care of it as soon as possible.

**Comment by findlabnet** [comment]
Thank you one more time: Version 1.x-1.0.15
