### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by bd0bd** [backdrop-contrib/seo_meta#3]
Sometimes it happens on /admin/content:

Notice: Undefined index: seo_meta in seo_meta_form_validate() (line 345 of /home/www/domain.com/modules/seo_meta/seo_meta.module).
Notice: Undefined property: Node::$seo_meta in seo_meta_node_update() (line 433 of /home/www/domain.com/modules/seo_meta/seo_meta.module).

**Comment by findlabnet** [comment]
Thanks, I'll check.

**Comment by bd0bd** [comment]
This error happens after I edit and save home page (after pressing SAVE button).

**Comment by findlabnet** [comment]
Thanks, any bugfix may produce new bug.

**Comment by bd0bd** [comment]
I know :smile:

**Comment by findlabnet** [comment]
Done, thanks again.

**Comment by bd0bd** [comment]
Yes, it's ok now.
Thank you!
