### ISSUE TITLE
Page 404 error has wrong title 

### ISSUE THREAD

**Issue by bd0bd** [backdrop-contrib/seo_meta#4]
"Append site name to page title" is unchecked but it appends the title.

It has URL 404 and Default 404 (not found) page is 404 at /admin/config/system/site-information

**Comment by findlabnet** [comment]
There is no appends, just BD default behavior.
Error pages 403 and 404 excluded from this module processing as pages do not have any value in SEO scope (but can produce side effects). If you need something exclusive on such pages - specialized template seems more attractive.

**Comment by bd0bd** [comment]
Appending **IS**! But it should not be. Because I have unchecked "Append site name to page title".

The thing is that everything was ok with base_meta.
If this is impossible to fix I will go back to base_meta :smile: Base_meta has no all these errors and problems.

**Comment by bd0bd** [comment]
```
do not have any value in SEO scope (but can produce side effects). 
```

I understand you but I need correct titles NOT only for SEO. I would like to have correct and custom titles in any case.

**Comment by findlabnet** [comment]
If module is named "SEO ...", why this module should run any non-SEO related tasks? Custom error pages is subject for another module, or some little work for themer.
BTW, what you mean

> ...all these errors and problems.

If you have any "errors and problems", feel free to open issue for each one. Your help is very appreciated.

**Comment by bd0bd** [comment]
It is about title customization and not SEO only, right?
In base_meta I have had custom title for 404 page.
In this module (people would expect it is better than base_meta) I do not have it :(

```
If module is named "SEO ...", why this module should run any non-SEO related tasks?
```

I think it is not productive to discuss this issue.
You can fix it or simply leave as is.
If you care about high standart of your module then probably you would fix it :smile: 

Thank you!

**Comment by findlabnet** [comment]
Fixed for custom error pages.

**Comment by bd0bd** [comment]
Vladimir, thank you!

I hope we both love everything was perfect and beautiful, even very minor details.
