### ISSUE TITLE
Marketing proposal

### ISSUE THREAD

**Issue by bd0bd** [backdrop-contrib/seo_meta#5]
I think it would be good to add at the bottom of page https://github.com/backdrop-contrib/base_meta 

Please note
This module is discontinued and ... SEO Meta Tags at https://github.com/backdrop-contrib/seo_meta

**Comment by findlabnet** [comment]
Thanks, it will be done at release time.

**Comment by bd0bd** [comment]
Release of what? SEO meta tags is released already, no?

**Comment by findlabnet** [comment]
Not yet.

**Comment by bd0bd** [comment]
I would like to ask you something about multilanguage configs. May I email you?

**Comment by findlabnet** [comment]
Yes. BTW, module is released, so this issue may be closed.

**Comment by bd0bd** [comment]
Ок. I'll write you today.
