### ISSUE TITLE
Errors in /admin/config/search/path/patterns

### ISSUE THREAD

**Issue by bd0bd** [backdrop-contrib/seo_meta#6]
Please take a look at /admin/config/search/path/patterns

Do not you have any errors?

I do have. But I am not sure if this is because of the SEO module.

**Comment by findlabnet** [comment]
No, I haven't errors on this path. Error(s) text may be helpful.

**Comment by bd0bd** [comment]
![ddd](https://cloud.githubusercontent.com/assets/13515302/17557176/e4a00178-5f1e-11e6-9be7-60c53c5622e4.png)

**Comment by findlabnet** [comment]
You can check your suspicion by temporarily disable "problematic" module.

**Comment by bd0bd** [comment]
Yes.
This happens because of Privatemsg module: https://github.com/backdrop-contrib/privatemsg/issues/8

**Comment by findlabnet** [comment]
Closed as not relevant.
