### ISSUE TITLE
Cannot install through Project Installer.

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/seo_meta#7]
> There was an error while installing SEO Meta Tags. Cannot extract temporary://update-cache-3707ac0c/1.x-1.0.4, not a valid archive.

**Comment by findlabnet** [comment]
Seems like environmental / casual error such as partial download.
Additionally, check the /tmp directory on your system (or whatever path you have BD's temporary path set to) and make sure it is writable by the user that your web server is running as.
Google for request _"Cannot extract temporary://update-cache-..."_ return bunch of links to  very similar questions of Drupal users over years.

**Comment by dyrer** [comment]
If this was the problem, I couldn't install any other modules. Is happening on specific modules. Maybe packages are broken.
I had to download these module, unzip them and uploaded again,

**Comment by findlabnet** [comment]
Maybe wrong permission set when packaging? 
After manually downloading and extracting module's archive, I found no reading/executing permissions for no one, exclude owner for **directories** of module itself and **sub-directories**.

![perms](https://cloud.githubusercontent.com/assets/11479969/18447968/8ab38e96-7931-11e6-9350-65a87df0cfbc.png)

As result this module can not be installed and generate 
`Warning: opendir(modules/seo_meta): failed to open dir: Permission denied in file_scan_directory() (line 2104 of /var/www/example.com/core/includes/file.inc).`
Of course, when permissions set properly, installation is successful.

**Comment by klonos** [comment]
@findlabnet I run this as system admin on my Windows laptop with UAC dissabled, so permissions is not an issue. As @dyrer said, this is not an issue with other projects. Only some specific ones display that behavior and seo_meta is one of them.

@quicksketch we recently solve this issue where the packaging script would mess up the URL of the project release node on backdropcms.org thus pointing to the wrong file. I thought that this was fixed though. Any ideas as to what might be going on here?

**Comment by findlabnet** [comment]
@klonos thanks, but so far as I can see, problem is permissions related. Or, I miss some API requirements for module? 

UPD. When Project Installer trying install another my module, "Easy XML sitemap" I see in `/tmp/update-cache-xxxxxxx/` file named "1.x-1.0.2" instead "easy_xmlsitemap.zip" and when I unzipped it manually - build directory is named "backdrop-contrib-easy_xmlsitemap-1c72471" instead "easy_xmlsitemap" (same directory permissions as above).

**Comment by findlabnet** [comment]
Finally, this is not a bug of module, but bad package. Today I've just increase version number to push out old package and downloaded file have right name and permissions.
I was so lucky with previous release dates: two my modules was damaged by packager failure.
