### ISSUE TITLE
Missing og:url

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/seo_meta#9]
When using the [Sharing debugger form Facebook](https://developers.facebook.com/tools/debug/sharing), it complaints of a missing og:url:

````
The 'og:url' property should be explicitly provided, even if a value can be inferred from other tags.
````

**Comment by findlabnet** [comment]
@robertgarrigos, thank you for reporting. I think `canonical URL` property value should be added automatically as property of this meta tag when filling out any other `og:some-tag`.
What do you think?

**Comment by robertgarrigos** [comment]
I agree

**Comment by findlabnet** [comment]
Release https://github.com/backdrop-contrib/seo_meta/releases/tag/1.x-1.0.10
Added option checkbox under default "OG" settings.
